spring:
  cloud:
    config:
    # 消息总线
    stream:
      kafka:
        binder:
          zk-nodes: 10.185.29.25:2181,10.185.29.25:2182,10.185.29.25:2183/kafka_test
          brokers: 10.127.220.91:9092,10.127.220.91:9093,10.127.220.91:9094

    # 开启跟踪事件消息（默认是false）
    bus:
      trace:
        enabled: true

# 关闭安全防护，能访问/bus/refresh, 不能直接访问/encrypt? 或者 http://user:password@IP:PORT/encrypt方式访问
management:
  security:
    enabled: false

## 用户认证，客户端应用接入时加入安全认证配置
security:
  user:
    name: configauth
    password: configauth123456
  # 只要这里开启，客户端必须配置用户认证（默认是true）
  basic:
    enabled: true

# 服务注册到Eureka上
eureka:
  client:
    service-url:
      defaultZone: http://10.185.30.207:1111/eureka/,http://10.185.30.213:1111/eureka/
  instance:
    # prefer-ip-address: true 和 手动设置的ip-address，优先获取手动设置的IP.
    prefer-ip-address: true
    # 自定义微服务实例名, 默认是${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ip-address: ${CONFIG_SERVER_PORT:127.0.0.1}

# 修改日志级别
#logging:
#  level:
#    org.springframework.cloud: debug
#    org.springframework.boot: debug
